name: Trigger auto deployment for accelquote

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/accelquote-AutoDeployTrigger-536fa8d7-3545-4c43-a943-35bad5cd5101.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACCELQUOTE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACCELQUOTE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACCELQUOTE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: regaccelquote.azurecr.io
          registryUsername: ${{ secrets.ACCELQUOTE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACCELQUOTE_REGISTRY_PASSWORD }}
          containerAppName: accelquote
          resourceGroup: rg_accelquote
          imageToBuild: regaccelquote.azurecr.io/accelquote:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


